#node
node:
  image: node:9.4.0
  ports:
    - "80:80"
  volumes:
    - ./node/:/node/
  environment:
    - "TZ=Japan"
  working_dir: /node
  command: npm start
  links:
    - mysql
  
mysql:
  image: mysql:5.7.16
  container_name: mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
  #command: --secure-file-priv="" --character-set-server=utf8 --collation-server=utf8_unicode_ci --sql_mode='STRICT_ALL_TABLES,ERROR_FOR_DIVISION_BY_ZERO,PIPES_AS_CONCAT'
  volumes:
    - ./mysql/volumes:/var/lib/mysql
  ports:
    - "3306:3306"
